### ISSUE TITLE
ImageSearch-20200212的依赖alibabacloud/openplatform-20191219的命名空间问题

### ISSUE THREAD

**Issue by KINGXINL** [aliyun/alibabacloud-sdk#346]
https://github.com/alibabacloud-sdk-php/ImageSearch-20200212
[ImageSearch.php](https://github.com/alibabacloud-sdk-php/ImageSearch-20200212/blob/0.2.12/src/ImageSearch.php)  里面的依赖alibabacloud/openplatform-20191219的命名空间问题 
原代码是AlibabaCloud\SDK\OpenPlatform\V20191219\OpenPlatform\AuthorizeFileUploadRequest
正确的应该是AlibabaCloud\SDK\OpenPlatform\V20191219\Models\AuthorizeFileUploadRequest;

**Comment by AxiosLeo** [comment]
Thanks, Fixed.

[ImageSearch Client Code](https://github.com/alibabacloud-sdk-php/ImageSearch-20200212/blob/b285d38f49752d7b99ae2e8cc7c4c88fe676eaa7/src/ImageSearch.php#L18)
