### ISSUE TITLE
composer下来代码不对

### ISSUE THREAD

**Issue by true2009fans** [aliyun/alibabacloud-sdk#366]
执行 composer require alibabacloud/opensearch 后代码跟github上不一致，只有V20171225/OpenSearchApiResolver.php 一个文件, 请帮忙看下是不是地址指定错了

**Comment by AxiosLeo** [comment]
找错 github 仓库了

alibabacloud/opensearch 这个包在这里 https://github.com/alibabacloud-sdk-php/opensearch
 
https://github.com/alibabacloud-sdk-php/opensearch/blob/master/OpenSearch.php
通过这个文件使用

使用方法参考下面这个链接的 readme
https://github.com/aliyun/openapi-sdk-php-client
