### ISSUE TITLE
go sdk imageSearch module issue 

### ISSUE THREAD

**Issue by mostend** [aliyun/alibabacloud-sdk#368]
$ go get -u -v github.com/alibabacloud-go/imagesearch-20200212
go: downloading github.com/alibabacloud-go/imagesearch-20200212 v1.1.4
go: github.com/alibabacloud-go/imagesearch-20200212 upgrade => v1.1.4
go get: github.com/alibabacloud-go/imagesearch-20200212@v1.1.4: parsing go.mod:
	module declares its path as: github.com/alibabacloud-go/imageSearch-20200212
	        but was required as: github.com/alibabacloud-go/imagesearch-20200212

should be modify document or module name. 

have a nice day.

**Comment by wenzuochao** [comment]
I'm sorry for that. Now you can pull the latest version of github.com/alibabacloud-go/imagesearch-20200212. Thanks for your support.

**Comment by wenzuochao** [comment]
I will close the issue. If you have other questions. Welcome to open a new issue. 
Have a nice day!
