### ISSUE TITLE
使用ocr20191230进行版本升级后，原有的代码无法正常运行，抛出异常：com.aliyun.tea.TeaException: POST requires exactly one file upload per request.

### ISSUE THREAD

**Issue by canglongxiang** [aliyun/alibabacloud-sdk#389]
我在使用“身份证”识别的方法，对本地上传的图片进行识别，代码如下：

> // 设置参数
        config = new Config();
        config.accessKeyId = ACCESS_KEY_ID;
        config.accessKeySecret = SECRET;
        config.regionId = REGION_ID;

> RecognizeIdentityCardAdvanceRequest request = new RecognizeIdentityCardAdvanceRequest();
        request.setImageURLObject(inputStream);
        request.setSide(side.getSide());

> // 构建请求
            Client client = this.buildClientInstance();
            RuntimeOptions runtimeOptions = this.buildRuntimeOptionsInstance();

            // 调用SDK，进行“身份证”识别
            RecognizeIdentityCardResponse response = client.recognizeIdentityCardAdvance(request, runtimeOptions);
            log.debug("调用“身份证”识别SDK收到的响应数据：{}", ObjectMapperUtils.buildInstance().writeValueAsString(response));

上述代码片段，在以下依赖情况时可以**正常运行**：

> com.aliyun:ocr20191230:**0.0.6**
com.aliyun:aliyun-java-sdk-core:4.5.17
com.squareup.okhttp3:okhttp:4.9.0

当我讲com.aliyun:ocr20191230升级到**0.1.1**和**0.2.16**时，均出现下面的错误：

> com.aliyun.tea.TeaException: POST requires exactly one file upload per request.
	at com.aliyun.oss.Client.postObject(Client.java:5399) ~[oss-client-2.0.1.jar:na]
	at com.aliyun.ocr20191230.Client.recognizeIdentityCardAdvance(Client.java:605) ~[ocr20191230-0.1.1.jar:na]

**Comment by yndu13** [comment]
需要刷新一下com.aliyun:ocr20191230的依赖com.aliyun:tea，请依赖1.1.5版本，也就是最新版本，或者1.1.4版本之前版本，不要依赖1.1.4版本，其存在部分问题。
```xml
<dependency>
  <groupId>com.aliyun</groupId>
  <artifactId>tea</artifactId>
  <version>1.1.5</version>
</dependency>
```

**Comment by canglongxiang** [comment]
com.aliyun:**tea**，是由com.aliyun.**ocr20191230**:**0.2.16**版本所引进的依赖，已经是1.1.5版本了。
![image](https://user-images.githubusercontent.com/5906745/104177346-91c3c380-5443-11eb-8b45-c1aa7c3997b5.png)

**Comment by canglongxiang** [comment]
在强制声明了引用的依赖：`com.aliyun:tea:1.1.5` 之后，仍然是相同的错误信息。

**Comment by HuangYingcong** [comment]
同样问题, com.aliyun:tea:1.1.6 貌似有效

**Comment by canglongxiang** [comment]
> 同样问题, com.aliyun🍵1.1.6 貌似有效

感谢，在将依赖 `com.aliyun:tea` 升级到 **1.1.6** 版本后，问题解决。
