### ISSUE TITLE
sdk问题

### ISSUE THREAD

**Issue by oceaneys** [aliyun/alibabacloud-sdk#393]
1. alibabacloud_aas20150701.client中有代码from Tea.core import TeaCore
可以通过pip install Tea, 但是安装后是tea而不是Tea，运行时依赖报错。
当然，手工把包名tea修改成Tea之后，不再报错
这里需要确认下pip下在的tea和代码中的Tea是不是一个茶，标准怎么定？

2. 在调用get_session_info_by_ticket时报错：
![image](https://user-images.githubusercontent.com/12001742/110090771-9d43c300-7dd2-11eb-8e60-67795098ff48.png)

**Comment by xiaofeige** [comment]
垃圾sdk, 不知道Tea包到底是哪个，文档里面写的需要安装的依赖根本装不上Tea

**Comment by Cherrymelon** [comment]
确实十分抽象，原来别人之前说远离阿里，不然会变得不幸，居然是真的
可能的解决办法，卸载 python 自带的 tea 包
`pip uninstall tea `

安装阿里的破包
`pip install alibabacloud-tea`
现在应该能够成功运行了

**Comment by bingobird** [comment]
"但是安装后是tea而不是Tea，运行时依赖报错。
当然，手工把包名tea修改成Tea之后，不再报错"--同样碰到了，SDK写得太烂了

**Comment by TsinghuaDream** [comment]
Tea包不是python自带的包，这个包的安装一般是因为pycharm的自动检查，因为我们包名是alibabacloud-tea，但引用的类是Tea。

遇到该问题，请同时pip uninstall tea和alibabacloud-tea，再安装alibabacloud-tea 即可重建索引，解决问题。
