### ISSUE TITLE
alibabacloud-go/ververica-20220718 is not updated to the latest version (1.0.3)

### ISSUE THREAD

**Issue by cofyc** [aliyun/alibabacloud-sdk#401]
In this commit (https://github.com/aliyun/alibabacloud-sdk/commit/c2e6b3f22052dddb5ba7f91697212dd4e5bed3a1), the `ververica-20220718` is updated to v1.0.3. However, alibabacloud-go/ververica-20220718 is not updated. The latest (2023-07-13) is [v1.0.0](https://github.com/alibabacloud-go/ververica-20220718/tree/v1.0.0).

**Comment by CodeSpaceiiii** [comment]
The version has been updated. If you encounter any issues in the future, you can reach out to us through the ticketing system.
