### ISSUE TITLE
想吐槽一下，这个包命名规范是谁想出来的

### ISSUE THREAD

**Issue by sunxunkang** [aliyun/alibabacloud-sdk#402]
包名打上这个日期是干啥用的，版本控制？？？github.com/alibabacloud-go/ram-20150501/v2

**Comment by abrahamgreyson** [comment]
小镇做题家背诵了大量的面试题，于是不得不放弃最基本的软件工程知识。

**Comment by CodeSpaceiiii** [comment]
你好，这个问题短期内没办法解决。
这个日期版本是对应的云产品初始化API服务的版本，不完全是日期，但绝大部分是日期，您可以理解为这个是ram服务在2015-05-01初始化的API版本。
