### ISSUE TITLE
sdk 逻辑混乱至极，文档更新缓慢，甚至不更新，恶心吐了...

### ISSUE THREAD

**Issue by tiancheng92** [aliyun/alibabacloud-sdk#406]
### 先以kv_store举例
> CreateTairInstance 用来创建Tair的云云原生实例
> CreateInstance 用来创建redis实例，以及Tair的经典版内存型实例

* 哪个小天才教你这么划分接口的？
    * CreateTairInstance接口中InstanceType 为存储类型 枚举值为： tair_rdb、tair_scm、tair_essd
    * CreateInstance接口中InstanceType 为实例类型 枚举值为： Redis、Memcache？（为啥会有Memcache）
    * 到了DescribeInstances中返回的InstanceType 文档的枚举值为：Redis、Memcache、Tair，但实际的返回值却包含了tair_rdb、tair_scm、tair_essd、Redis四种？ 通过InstanceType查询，当InstanceType=Redis时，会返回tair_xxx的数据，what the fuck？？？

> DescribeInstances 用来查询所有实例
* 但是文档中又没有明确告知如何通过DescribeInstances返回的实例信息区分，什么狗屁经典版，到底是Redis还是Tair引擎
因为你们返回的Engine字段只会统一返回Redis

> 根据产品型号也无法直接判断
* 因为在控制台上显示的Tair实例，部分型号也会是以redis开头的

> 为啥不直接获取型号列表信息
* 因为你们的型号信息整整嵌套9层循环！！！筛选条件还是不完整的

* 文档中也不标注哪些参数是互斥的

> DescribeInstanceAttribute接口
* 我明明只查询了一个实例却给我2个返回？仔细观察才发现一个是只有公网地址，一个是内网地址+其他属性，拜托，哪有这么玩的，合并下会死啊

### 成本相关接口
* sdk的结构体和真实的返回毫不相关，导致映射失败，我只能获取原始的字节码自己分析
* 这几个月从接口获取的数据还和控制台有所出入（就是从你们裁员哪个月开始的）

# 未完待续

**Comment by abrahamgreyson** [comment]
没人看的 ，这家公司意识不到 SDK 是云服务最重要的门面之一。
技术人员用起来都不舒服， 有客户都见鬼了。

**Comment by xpol** [comment]
OSS sdk 文档链接过去的是通用接口文档。示例里面给的是 facebody20191230 的代码。
怎么生成一个 Config 对象都不说。wtf。
你还要别人举一反三啊？
那我照着你的 facebody 的格式初始化 oss， 他妈的 typescript 报错啊！
垃圾

**Comment by CodeSpaceiiii** [comment]
> OSS sdk 文档链接过去的是通用接口文档。示例里面给的是 facebody20191230 的代码。 怎么生成一个 Config 对象都不说。wtf。 你还要别人举一反三啊？ 那我照着你的 facebody 的格式初始化 oss， 他妈的 typescript 报错啊！ 垃圾

请参考 https://help.aliyun.com/zh/oss/developer-reference/installation-7?spm=a2c4g.11186623.help-menu-31815.d_3_3_1_0.50f34b25wMcBRI&scm=20140722.H_32068._.OR_help-T_cn#DAS#zh-V_1 这里的说明文档。

https://help.aliyun.com/zh/oss/developer-reference/create-a-bucket-4?spm=a2c4g.11186623.help-menu-31815.d_3_3_1_4_0.2a8077718GFSFg&scm=20140722.H_32071._.OR_help-T_cn#DAS#zh-V_1 这里有示例的代码。

**Comment by CodeSpaceiiii** [comment]
> 没人看的 ，这家公司意识不到 SDK 是云服务最重要的门面之一。 技术人员用起来都不舒服， 有客户都见鬼了。

感谢您的反馈，我们内部有一些手段会来检查云产品发布的各个OpenAPI的质量，但确实有一些历史的问题导致出入参值的映射有不一致的问题。这些修改会导致BC，因此不太能直接修改。

高级的封装比如terraform中我们在内部处理了这些不一致，此外也尝试从CloudControl API来解决此类问题，https://help.aliyun.com/zh/cloud-control-api?spm=a2c4g.11186623.d_help_search.i2
