### ISSUE TITLE
Breaking change in a Patch version v3.2.1 -> v3.2.2

### ISSUE THREAD

**Issue by Skarlso** [aliyun/alibabacloud-sdk#409]
https://github.com/alibabacloud-go/kms-20160120/commit/0801a4af3e44f1cec3c0793a407b9749b0eee3ef#diff-bd3a55a72186f59e2e63efb4951573b2f9e4a7cc98086e922b0859f8ccc1dd09R9236

```diff
-	VersionStages *GetSecretValueResponseBodyVersionStages `json:"VersionStages,omitempty" xml:"VersionStages,omitempty" type:"Struct"`
+	VersionStages []*string `json:"VersionStages,omitempty" xml:"VersionStages,omitempty" type:"Repeated"`
```

Please be more careful with your version releases.

```diff
-	github.com/alibabacloud-go/kms-20160120/v3 v3.2.1
+	github.com/alibabacloud-go/kms-20160120/v3 v3.2.2
```

**Comment by akayj** [comment]
SAME! 

upgrading to v3.2.2, my code breaks. debug it found that `VersionStages` is a map not a list,
panic with this:
```client.GetSecretValueResponse.Body: client.GetSecretValueResponseBody.VersionStages: []*string: decode slice: expect [ or n, but found {, error found in #10 byte of ...|nStages":{"VersionSt|..., bigger context ...|Generic","VersionId":"v20240716","VersionStages":{"VersionStage":["ACSCurrent"]}},"headers":{"connec|...```

**Comment by CodeSpaceiiii** [comment]
I’m very sorry, please upgrade to version v3.2.3. We have further enhanced control in our processes to avoid similar issues in the future.

**Comment by Skarlso** [comment]
Thank you! :) No worries, these things sometimes slip through. :)
